<p><strong>ID:</strong> <?php echo $usuarios->idusuarios; ?></p>
<p><strong>Nombre:</strong> <?php echo $usuarios->nombre_usuario; ?></p>
<p><strong>Apellido:</strong> <?php echo $usuarios->apellido_usuario; ?></p>
<p><strong>Telefono:</strong> <?php echo $usuarios->telefono; ?></p>
<p><strong>Ciudad:</strong> <?php echo $usuarios->ciudad_usuario; ?></p>
<p><strong>E-Mail:</strong> <?php echo $usuarios->email_usuario; ?></p>
<p><strong>User:</strong> <?php echo $usuarios->user_usuario; ?></p>
<p><strong>Clave:</strong> <?php echo $usuarios->clave_usuario; ?></p>
<p><strong>Rol:</strong> <?php echo $usuarios->rol_id; ?></p>
<p><strong>Estado:</strong> <?php echo $usuarios->estado_usuario; ?></p>